;; This logfile was generated automatically by `xindy'
;; at 18.04.2021  22:12:26
;; Indexstyle: "/var/folders/jg/trxh5xc5067bgmplfk15frqh0000gn/T/hELr0IdSCT", Rawindex: "/var/folders/jg/trxh5xc5067bgmplfk15frqh0000gn/T/ghXms200sC", Output: "final_report.acr"


Building indexentry-tree:
Hierdepth of index is :TREE

sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)

Forming letter-groups:
Letter-group: "Ð€Ë" -> "S"
Letter-group: "´œ»" -> "L"
Letter-group: "®€" -> "K"
Letter-group: "Ë€" -> "R"
Letter-group: "Ë†»†" -> "R"
Letter-group: "†Ð€" -> "C"
Letter-group: "Ë†Ð" -> "R"
Letter-group: "ÐÚ´" -> "S"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "†Ð€" -> "C"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "®€" -> "K"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "´œ»" -> "L"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ë†»†" -> "R"
sort-indexentries: (FORWARD BACKWARD FORWARD FORWARD)
Letter-group: "Ð€Ë" -> "S"